// Healthcare services catalog (A-U)
export const services = [
  {
    slug: 'healthcare-data-management',
    letter: 'A',
    title: 'Healthcare Data Management & Interoperability',
    short: 'Unified FHIR/HL7 data exchange that connects every system in your enterprise.',
    icon: 'Database',
    tagline: 'One source of truth across every clinical, operational and administrative system.',
    description: 'Build a single, interoperable healthcare data fabric using FHIR R4, HL7 v2/v3, CDA and modern streaming pipelines. We unify fragmented EHR/EMR systems, lab analyzers, imaging archives and third-party platforms into a real-time, governed clinical data exchange.',
    features: ['FHIR R4 Integration','HL7 v2 / v3 Messaging','EHR / EMR Connectivity','Unified Patient Records (UPR)','Healthcare Data Platforms','Real-time Data Transformation','Clinical Data Exchange & HIE'],
    tech: ['FHIR R4','HL7','Mirth Connect','Apache Kafka','Azure Health Data Services','Google Cloud Healthcare API','Snowflake','dbt','Databricks'],
    benefits: ['360° patient view across facilities','Eliminate data silos between departments','Faster onboarding of new clinical apps','Built-in audit, governance and lineage','Lower integration costs by 40–60%'],
    useCases: ['National HIE rollouts','Multi-hospital network consolidation','Payer–provider data exchange','Clinical research data harmonization'],
  },
  {
    slug: 'healthcare-ai-automation',
    letter: 'B',
    title: 'Healthcare AI & Intelligent Automation',
    short: 'Generative AI, agents and copilots purpose-built for clinical and operational workflows.',
    icon: 'Bot',
    tagline: 'Autonomous healthcare operations driven by enterprise-grade AI.',
    description: 'Deploy production-grade generative AI, autonomous agents and copilots that augment clinicians, automate back-office work and orchestrate complex healthcare workflows — with safety, compliance and human-in-the-loop controls.',
    features: ['Generative AI for Clinical Docs','Autonomous AI Agents','Conversational AI & Voice','Intelligent Workflow Automation','Autonomous Healthcare Operations','AI Copilots for Clinicians'],
    tech: ['GPT-class LLMs','LangGraph','Vector DBs','RAG Pipelines','Azure OpenAI','AWS Bedrock','Vertex AI'],
    benefits: ['Reduce clinical documentation time by 60%','Cut administrative cost-to-serve','24/7 patient-facing AI experiences','Predictable, auditable AI outputs'],
    useCases: ['Ambient clinical documentation','Prior authorization automation','Patient triage and routing','Revenue-cycle AI agents'],
  },
  {
    slug: 'healthcare-analytics-bi',
    letter: 'C',
    title: 'Healthcare Analytics & Business Intelligence',
    short: 'Executive, operational and clinical analytics with predictive intelligence at scale.',
    icon: 'BarChart3',
    tagline: 'From raw clinical data to executive insight — in seconds.',
    description: 'Modern healthcare BI stack covering clinical, operational, financial and quality analytics. Predictive models, real-time dashboards and KPI war-rooms designed for hospital executives, service lines and clinical leaders.',
    features: ['Clinical Analytics','Operational Dashboards','Predictive Analytics','Executive Reporting','KPI Monitoring','Healthcare BI Systems'],
    tech: ['Power BI','Tableau','Looker','dbt','Snowflake','BigQuery','Python ML'],
    benefits: ['Real-time KPI visibility','Predict ED surges 24h in advance','Length-of-stay optimization','Service-line P&L clarity'],
    useCases: ['CEO operational dashboards','Quality and value-based care reporting','Capacity and bed management','Population health analytics'],
  },
  {
    slug: 'smart-hospital-operations',
    letter: 'D',
    title: 'Smart Hospital & Real-Time Operations',
    short: 'AI command centers and event-driven systems for real-time hospital orchestration.',
    icon: 'Activity',
    tagline: 'Your hospital, orchestrated like an airline operations center.',
    description: 'Build a real-time, event-driven smart hospital with AI command centers, situational awareness, bed flow, transport and emergency coordination — all powered by streaming data and predictive operational AI.',
    features: ['Smart Hospital Infrastructure','Real-Time Operational Intelligence','Emergency Coordination','Situational Awareness Walls','AI Command Centers','Event-Driven Systems'],
    tech: ['Apache Kafka','Apache Flink','Redis','WebSockets','IoT Edge','Time-series DBs'],
    benefits: ['ED throughput +25%','Transfer & discharge acceleration','Real-time crisis coordination','Lower length-of-stay variability'],
    useCases: ['Hospital command centers','Multi-site capacity orchestration','Mass-casualty incident response','OR & ICU optimization'],
  },
  {
    slug: 'clinical-decision-support',
    letter: 'E',
    title: 'Clinical Decision Support & Patient Intelligence',
    short: 'AI-guided clinical decisions, risk prediction and personalized treatment intelligence.',
    icon: 'Brain',
    tagline: 'Augmenting every clinical decision with precision intelligence.',
    description: 'Evidence-based CDS combined with proprietary clinical AI models for risk stratification, deterioration prediction, treatment recommendations and outcome forecasting — embedded directly into clinician workflows.',
    features: ['AI Clinical Guidance','Patient Risk Prediction','Personalized Medicine','Treatment Intelligence','Patient Outcome Forecasting'],
    tech: ['Clinical LLMs','XGBoost','PyTorch','SMART on FHIR','CDS Hooks'],
    benefits: ['Earlier sepsis & deterioration detection','Reduced readmissions','Personalized care pathways','Higher clinical quality scores'],
    useCases: ['Sepsis prediction','Oncology treatment guidance','Chronic disease management','ICU deterioration alerts'],
  },
  {
    slug: 'laboratory-information-systems',
    letter: 'F',
    title: 'Laboratory Information Systems (LIS)',
    short: 'End-to-end LIS with specimen tracking, analyzer integration and intelligent workflows.',
    icon: 'FlaskConical',
    tagline: 'A next-generation LIS engineered for high-throughput precision laboratories.',
    description: 'Modern, modular LIS platform covering pre-analytical, analytical and post-analytical workflows — with specimen tracking, analyzer interfacing, diagnostic reporting and full lab management.',
    features: ['Specimen Tracking','Laboratory Workflow Automation','Diagnostic Reporting','Analyzer Integration','Lab Management Systems'],
    tech: ['ASTM','HL7 LAB','LOINC','Barcode/RFID','Middleware'],
    benefits: ['TAT reduction 30–50%','Fewer specimen errors','Higher analyzer utilization','Audit-ready quality records'],
    useCases: ['Reference laboratories','Hospital labs','Public health labs','Genomics labs'],
  },
  {
    slug: 'pathology-diagnostics',
    letter: 'G',
    title: 'Pathology & Diagnostics',
    short: 'Digital pathology, molecular diagnostics, genomics and AI-driven imaging.',
    icon: 'Microscope',
    tagline: 'Precision diagnostics powered by AI and digital pathology.',
    description: 'Comprehensive diagnostic platform spanning digital pathology, molecular diagnostics, cytogenetics, genomics and AI-augmented imaging — designed for precision medicine programs.',
    features: ['Digital Pathology','Molecular Diagnostics','Cytogenetics','Genomics','Precision Medicine','Diagnostic Imaging'],
    tech: ['DICOM','WSI Viewers','PyTorch CV','Bioinformatics Pipelines','NGS'],
    benefits: ['Faster turnaround on complex cases','AI-assisted pathologist productivity','Standardized digital workflows','Enabled precision medicine'],
    useCases: ['Tumor boards','Cancer genomics','Rare disease diagnostics','Tele-pathology networks'],
  },
  {
    slug: 'blood-bank-transfusion',
    letter: 'H',
    title: 'Blood Bank & Transfusion Management',
    short: 'End-to-end blood center operations, donor management and transfusion safety.',
    icon: 'Droplets',
    tagline: 'A safer, smarter blood supply chain — from donor to recipient.',
    description: 'Enterprise blood bank platform covering donor management, inventory, cross-match, issuance and transfusion tracking — with full traceability and regulatory compliance.',
    features: ['Blood Inventory Management','Donor Management','Transfusion Tracking','Blood Center Operations'],
    tech: ['ISBT 128','HL7','RFID Tags','Cold-chain IoT'],
    benefits: ['Zero-defect transfusion safety','Real-time inventory visibility','Optimized donor recruitment','Full chain-of-custody'],
    useCases: ['National blood services','Multi-hospital blood networks','Disaster preparedness'],
  },
  {
    slug: 'patient-monitoring-emergency',
    letter: 'I',
    title: 'Patient Monitoring & Emergency Systems',
    short: 'ICU monitoring, real-time alerts and AI-powered emergency coordination.',
    icon: 'HeartPulse',
    tagline: 'Continuous patient intelligence — from ICU to ambulance to ED.',
    description: 'Real-time patient monitoring across ICU, step-down, ward and pre-hospital settings, with AI-based deterioration detection, critical alert routing and ambulance/ED coordination.',
    features: ['ICU Monitoring','Real-Time Patient Monitoring','Critical Alerts','Ambulance Coordination','Emergency AI Systems'],
    tech: ['HL7 Device','IoMT Gateways','MQTT','Edge AI'],
    benefits: ['Earlier rapid-response activations','Reduced alert fatigue','Pre-hospital clinical visibility','Better ED hand-offs'],
    useCases: ['Tele-ICU programs','EMS dispatch optimization','Code-blue AI assist'],
  },
  {
    slug: 'governance-compliance-security',
    letter: 'J',
    title: 'Healthcare Governance, Compliance & Security',
    short: 'Enterprise data governance, compliance automation and zero-trust security.',
    icon: 'ShieldCheck',
    tagline: 'Security and compliance, engineered into every layer.',
    description: 'Healthcare-grade governance, compliance and security frameworks — including HIPAA, GDPR, NPHIES, HITRUST, NCA and ISO 27001 — with automated controls and continuous assurance.',
    features: ['Data Governance','Compliance Automation','Metadata Management','Security Frameworks','Audit Systems','Regulatory Compliance'],
    tech: ['Collibra','Purview','Vault','SIEM','Zero-trust Networking'],
    benefits: ['Continuous compliance posture','Automated audit evidence','Reduced breach risk','Fast regulator response'],
    useCases: ['HIPAA & GDPR programs','National regulator audits','Cross-border data flows'],
  },
  {
    slug: 'healthcare-cloud-infrastructure',
    letter: 'K',
    title: 'Healthcare Cloud & Infrastructure Modernization',
    short: 'AI-ready hybrid cloud platforms purpose-built for regulated healthcare workloads.',
    icon: 'CloudCog',
    tagline: 'Modernize without compromise — cloud, hybrid and sovereign.',
    description: 'Reference architectures and migration accelerators for healthcare cloud — across Azure, AWS, GCP and sovereign clouds — with FHIR-native data services, AI platforms and DR-grade resilience.',
    features: ['Cloud Migration','Hybrid Infrastructure','AI-Ready Cloud Platforms','Enterprise Healthcare Architecture'],
    tech: ['Azure','AWS','GCP','Kubernetes','Terraform','Sovereign Cloud'],
    benefits: ['Lower TCO','Elastic AI compute','Regulator-friendly data residency','Resilient multi-region DR'],
    useCases: ['Hospital cloud-of-clouds','Sovereign healthcare clouds','AI compute platforms'],
  },
  {
    slug: 'workflow-operational-optimization',
    letter: 'L',
    title: 'Healthcare Workflow & Operational Optimization',
    short: 'Adaptive workflows, scheduling and AI-driven operational automation.',
    icon: 'Workflow',
    tagline: 'Every workflow, continuously optimized by data and AI.',
    description: 'Optimize scheduling, resource allocation and clinical/operational workflows using adaptive automation, simulation and reinforcement learning — tuned for healthcare constraints.',
    features: ['Scheduling Optimization','Adaptive Workflows','Resource Allocation','Operational Automation'],
    tech: ['Camunda','Process Mining','OR Tools','RL Models'],
    benefits: ['Higher OR & clinic utilization','Reduced overtime','Predictable patient flow','Lower no-show rates'],
    useCases: ['Surgical scheduling','Outpatient clinic flow','Workforce optimization'],
  },
  {
    slug: 'patient-physician-engagement',
    letter: 'M',
    title: 'Patient & Physician Engagement Platforms',
    short: 'Patient portals, physician portals and AI-driven contact center automation.',
    icon: 'Users',
    tagline: 'A digital front door — for patients, physicians and care teams.',
    description: 'Modern digital engagement platforms — patient portals, physician portals, AI contact centers and omnichannel messaging — that drive access, adherence and satisfaction.',
    features: ['Patient Portals','Physician Portals','AI Engagement Systems','Contact Center Automation'],
    tech: ['Next.js','React Native','Twilio','Conversational AI'],
    benefits: ['Higher patient retention','Lower call-center cost','Physician satisfaction','Better access metrics'],
    useCases: ['National patient apps','Provider networks','Insurance member apps'],
  },
  {
    slug: 'pharma-life-sciences',
    letter: 'N',
    title: 'Pharmaceutical & Life Sciences Solutions',
    short: 'Analytics, research and intelligence platforms for pharma & life sciences.',
    icon: 'Pill',
    tagline: 'Accelerating drug discovery, research and commercial intelligence.',
    description: 'AI-powered platforms for pharma analytics, drug research, clinical trial intelligence and commercial insights — built for regulated life-sciences environments.',
    features: ['Pharma Analytics','Drug Research Platforms','Clinical Research Systems','Life Sciences Intelligence'],
    tech: ['CDISC','GxP Cloud','Bioinformatics','Generative AI'],
    benefits: ['Faster trial recruitment','Real-world evidence at scale','Optimized commercial spend','GxP-ready platforms'],
    useCases: ['Clinical trial intelligence','Real-world evidence','Commercial analytics'],
  },
  {
    slug: 'research-biobanking',
    letter: 'O',
    title: 'Healthcare Research & Biobanking',
    short: 'Biospecimen tracking, research analytics and synthetic healthcare data platforms.',
    icon: 'Dna',
    tagline: 'Industrial-grade infrastructure for healthcare research and biobanks.',
    description: 'Biobanking, biospecimen tracking, research analytics and synthetic-data platforms enabling national research programs and translational science.',
    features: ['Biospecimen Tracking','Research Analytics','Synthetic Healthcare Data','Biorepository Systems'],
    tech: ['ISBER','LIMS','OMOP CDM','Synthea','Differential Privacy'],
    benefits: ['Accelerated research velocity','Privacy-preserving collaboration','Long-term specimen integrity','Cross-institution data sharing'],
    useCases: ['National biobanks','Population genomics','Translational research'],
  },
  {
    slug: 'public-health-biosurveillance',
    letter: 'P',
    title: 'Public Health & Biosurveillance',
    short: 'Outbreak intelligence, disease monitoring and population-level dashboards.',
    icon: 'Globe2',
    tagline: 'Real-time intelligence to protect populations.',
    description: 'Public-health and biosurveillance platforms with disease monitoring, outbreak detection, epidemiological analytics and national-level dashboards.',
    features: ['Disease Monitoring','Outbreak Intelligence','Epidemiological Analytics','Public Health Dashboards'],
    tech: ['GIS','Geo-streaming','Bayesian Models','LLM Triage'],
    benefits: ['Earlier outbreak detection','Coordinated national response','Evidence-based public policy','Open-data publishing'],
    useCases: ['Ministry-of-health dashboards','Pandemic preparedness','Vaccination programs'],
  },
  {
    slug: 'revenue-cycle-finance',
    letter: 'Q',
    title: 'Revenue Cycle & Healthcare Finance',
    short: 'Billing, claims, denial management and AI-driven revenue optimization.',
    icon: 'Wallet',
    tagline: 'Maximize collections, minimize denials — automatically.',
    description: 'End-to-end revenue-cycle platform with billing, claims processing, denials AI, payer integration and Medicare/Medicaid compliance — driving measurable margin improvement.',
    features: ['Billing Systems','Claims Processing','Revenue Optimization','Medicare Compliance'],
    tech: ['X12 EDI','ICD-10','CPT','NPHIES','AI Denials'],
    benefits: ['Higher first-pass yield','Lower denial rates','Faster DSO','Cleaner coding'],
    useCases: ['Hospital RCM','Physician group billing','Payer integration'],
  },
  {
    slug: 'medical-device-iot',
    letter: 'R',
    title: 'Medical Device & IoT Integration',
    short: 'IoMT connectivity, edge AI and device data normalization at scale.',
    icon: 'Cpu',
    tagline: 'Every medical device, securely connected and intelligently observed.',
    description: 'Connect bedside monitors, infusion pumps, ventilators, wearables and lab analyzers via a secure IoMT gateway — with edge AI, normalization and full lifecycle management.',
    features: ['IoMT Systems','Device Connectivity','Sensor Integration','Edge AI Systems'],
    tech: ['MQTT','OPC-UA','HL7 Device','Edge Kubernetes','TinyML'],
    benefits: ['Standardized device data','Edge processing for low latency','Continuous device observability','Secure device-to-cloud'],
    useCases: ['Tele-ICU','RPM programs','Smart-ward rollouts'],
  },
  {
    slug: 'consulting-digital-transformation',
    letter: 'S',
    title: 'Healthcare Consulting & Digital Transformation',
    short: 'Strategy, AI adoption roadmaps and enterprise healthcare modernization.',
    icon: 'Rocket',
    tagline: 'Executive partners for healthcare digital transformation.',
    description: 'C-suite consulting on AI strategy, digital transformation, enterprise modernization and operating-model redesign — delivered by clinicians, technologists and former hospital executives.',
    features: ['AI Transformation Strategy','Digital Healthcare Consulting','Enterprise Modernization','AI Adoption Roadmaps'],
    tech: ['HIMSS EMRAM','HL7 Maturity','Healthcare TOGAF'],
    benefits: ['Board-ready strategy','Funded business cases','Vendor-neutral guidance','Measurable transformation KPIs'],
    useCases: ['CEO digital agenda','Post-merger integrations','National health programs'],
  },
  {
    slug: 'quality-laboratory-qa',
    letter: 'T',
    title: 'Healthcare Quality & Laboratory QA',
    short: 'QA/QC, SOP management, validation and quality compliance systems.',
    icon: 'BadgeCheck',
    tagline: 'Quality, validation and compliance — built into your operations.',
    description: 'QA/QC, SOP management, validation, calibration and quality-compliance systems for hospitals, labs and life-sciences — aligned to ISO 15189, CAP and JCI.',
    features: ['Laboratory QA/QC','SOP Management','Quality Compliance','Validation Systems'],
    tech: ['ISO 15189','CAP','CLSI','eQMS'],
    benefits: ['Audit-ready quality posture','Reduced quality incidents','Faster accreditation cycles','Strong clinical governance'],
    useCases: ['Lab accreditation programs','Hospital JCI prep','Validation pipelines'],
  },
  {
    slug: 'transplant-specialized-systems',
    letter: 'U',
    title: 'Transplant & Specialized Healthcare Systems',
    short: 'Immunogenetics, donor matching and specialized transplant systems.',
    icon: 'HeartHandshake',
    tagline: 'Specialized clinical systems for the most complex programs.',
    description: 'Immunogenetics, HLA typing, donor–recipient matching and specialized transplant systems — engineered for national transplant programs and tertiary centers.',
    features: ['Immunogenetics','Donor-Recipient Matching','Specialized Clinical Systems'],
    tech: ['HLA Typing','NGS','Matching Algorithms'],
    benefits: ['Better match outcomes','National donor registries','Specialized clinical safety','Research-grade longitudinal data'],
    useCases: ['National transplant programs','Bone-marrow registries','Solid-organ programs'],
  },
];

export const getServiceBySlug = (slug) => services.find(s => s.slug === slug);

export const stats = [
  { value: 250, suffix: '+', label: 'Healthcare Clients' },
  { value: 40, suffix: 'M+', label: 'Patient Records Unified' },
  { value: 99.99, suffix: '%', label: 'Uptime SLA' },
  { value: 18, suffix: '', label: 'Countries Served' },
];

export const partners = [
  { name: 'Vantiq', href: 'https://vantiq.com/' },
  { name: 'Elait Health', href: 'https://elait.health/' },
  { name: 'SoftComputer', href: 'https://www.softcomputer.com/' },
  { name: 'SDG Group', href: 'https://www.sdggroup.com/' },
  { name: 'Microsoft', href: 'https://www.microsoft.com/' },
  { name: 'AWS', href: 'https://aws.amazon.com/' },
  { name: 'Google Cloud', href: 'https://cloud.google.com/' },
];
